---
title: "Cornhole_2021_stats"
author: "Brian"
date: "2023-02-26"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(readr)
library(tidyverse)
library(scales)
library(DT)
```


```{r}
# data <- read.csv("STOR 538_ P1 - Sheet1.csv", header=TRUE, skip=1)
# data$Match. <- as.factor(data$Match.)
# data$Round. <- as.factor(data$Round.)
# data$Throw_Number <- as.factor(data$Throw_Number)
# data$Bag. <- as.factor(data$Bag.)


# data_cleaned <- data%>%
# filter(Round. != "FINAL")
```

# Data Configuration

```{r}
## Pull data in
Master <- read.csv("master.csv", header=TRUE, skip=1)
Game_scores <- read.csv("Game_scores.csv", header=TRUE)
Round_scores <- read.csv("Round_scores.csv", header=TRUE)

Master$Match <- as.factor(Master$Match)
Master$Round <- as.factor(Master$Round)
Master$Throw_Number <- as.factor(Master$Throw_Number)
Master$Bag_Number <- as.factor(Master$Bag_Number)
```

```{r}
## merge data

Cornhole <- merge(Master, Round_scores, by.x = c("Match", "Round"), by.y = c("Game_Number", "Round_Number"))
Cornhole <- merge(Cornhole, Game_scores, by.x = "Match", by.y = "Game_Number")
Cornhole <- Cornhole%>%
  select(-c("Player_1.y", "Player_2.y"))
```


## Data Preview

```{r}
head(Master)
```

## Variable Breakdown by Throws

```{r}
Throw_breakdown <- Master%>%
  group_by(Throw_Number)%>%
  summarise(total = n(),
            in_hole_pct = round(sum(In_Hole)/total*100,1),
            on_board_pct = round(sum(On_Board)/total*100,1),
            missed_board_pct = round(sum(Missed_Board)/total*100,1),
            avg_Own_bags_dragged = sum(Own_Other_Bags_Dragged_In)/total,
            avg_Opponent_Bags_Dragged_In = sum(Opponent_Bags_Dragged_In)/total,
            avg_Own_Other_Bags_Knocked_Off = sum(Own_Other_Bags_Knocked_Off)/total,
            avg_Opponent_Other_Bags_Knocked_Off = sum(Opponent_Other_Bags_Knocked_Off)/total,
            Hole_Blocked_Before_Throw_pct = round(sum(as.numeric(Hole_Blocked_Before_Throw))/total*100,1),
            Hole_Blocked_After_pct = round(sum(Hole_Blocked_After_Throw)/total*100,1))

Throw_breakdown
```

## Visualizing a Round

```{r}
in_hole_by_throw_plot <- plot(Throw_breakdown$Throw_Number, Throw_breakdown$in_hole_pct, xlab = "Throw", ylab = "in hole percentage")
in_hole_by_throw_plot
```

```{r}
blocked_by_throw_plot <- plot(Throw_breakdown$Throw_Number, Throw_breakdown$Hole_Blocked_Before_Throw_pct, xlab = "Throw", ylab = "Hole Blocked For Throw")
blocked_by_throw_plot
```

# Analysis with Metrics


## Throw Skill

### Average Toss Score (ATS)

```{r}
## Average Toss Score (ATS)

by_round_ATS <- Cornhole%>%
  group_by(Match, Round, Thrower)%>%
  summarise(ATS = (sum(On_Board) + 3*sum(In_Hole))/4)
# by_round_stats <- by_round_stats[order(by_round_stats$ATS),]

by_game_ATS <- Cornhole%>%
  group_by(Match, Thrower)%>%
  summarise(total_throws = n(),
            ATS = (sum(On_Board) + 3*sum(In_Hole))/total_throws)%>%
  ungroup()


```

## Board Management

### Cluttering

#### Blocks Created (BC)

```{r}
by_round_BC <- Cornhole%>%
  group_by(Match, Round, Thrower)%>%
  summarise(BC = sum(Strategic_Block_Created))
by_round_BC

by_game_BC <- Cornhole%>%
  group_by(Match, Thrower)%>%
  summarise(total_throws = n(),
            BC = sum(Strategic_Block_Created),
            NBC = BC/total_throws)
by_game_BC
```

#### Adjusted Blocks Created (ABC)

```{r}
blocks_created_breakdown <- Cornhole%>%
  filter(Strategic_Block_Created == 1)%>%
  select(Match, Round, Throw_Number, Thrower, Round_Winner)%>%
  mutate(winning_block = ifelse(Round_Winner == Thrower, 1, 0))%>%
  group_by(Throw_Number)%>%
  summarise(total = n(),
            win_pct = sum(winning_block)/total)

blocks_table <- Cornhole%>%
  filter(Strategic_Block_Created == 1)%>%
  select(Match, Round, Throw_Number, Thrower, Round_Winner)%>%
  mutate(winning_block = ifelse(Round_Winner == Thrower, 1, 0))

final_round_scores <- Master%>%
  filter(Throw_Number == 8)%>%
  select(1,2,8,9)%>%
  rename("Player1_Final_Score" = Player1_Round_Score)%>%
  rename("Player2_Final_Score" = Player2_Round_Score)

block_master <- Master%>%
  select(c(1:9,19:21))%>%
  mutate(Thrower_score_at_block = ifelse(Strategic_Block_Created == 1, ifelse(Thrower == Player_1, Player1_Round_Score, Player2_Round_Score), -1))%>%
  mutate(Opponent_score_at_block = ifelse(Strategic_Block_Created == 1, ifelse(Thrower == Player_1, Player2_Round_Score, Player1_Round_Score), -1))%>%
  merge(final_round_scores, by = c("Match", "Round"))%>%
  filter(Strategic_Block_Created == 1)%>%
  mutate(Thrower_Score_Diff = ifelse(Thrower == Player_1, Player1_Final_Score - Thrower_score_at_block, Player2_Final_Score - Thrower_score_at_block))%>%
  mutate(Opponent_Score_Diff = ifelse(Thrower == Player_1, Player2_Final_Score - Opponent_score_at_block, Player1_Final_Score - Opponent_score_at_block))%>%
  select(-c(3,8:12))%>%
  mutate(net_score_after_block = Thrower_Score_Diff - Opponent_Score_Diff)

mean(block_master$Thrower_score_at_block - block_master$Opponent_score_at_block)
mean(block_master$net_score_after_block)

## Block recovery score (NSAB)
by_game_NSAB <- block_master%>%
  group_by(Match, Thrower)%>%
  summarise(blocks = n(),
            total_NSAB = sum(net_score_after_block),
            NSAB_per_block = mean(net_score_after_block))

double_blocks <- blocks_table%>%
  group_by(Match, Round)%>%
  summarise(n = n())

by_round_NSAB <- block_master%>%
  group_by(Match, Round, Thrower)%>%
  summarise(blocks = n(),
            total_NSAB = sum(net_score_after_block),
            NSAB_per_block = mean(net_score_after_block))
view(by_round_NSAB)


blocks_created_breakdown
plot(blocks_created_breakdown$total, blocks_created_breakdown$win_pct)
text(blocks_created_breakdown$total, blocks_created_breakdown$win_pct, labels = blocks_created_breakdown$Throw_Number)
```


### Cleaning

#### Board Impact (BI)

```{r}
by_round_BI <- Cornhole%>%
  group_by(Match, Round, Thrower)%>%
  summarise(flat_BI = sum(Opponent_Other_Bags_Knocked_Off) + sum(Own_Other_Bags_Knocked_Off) + sum(Own_Other_Bags_Dragged_In) + sum(Opponent_Bags_Dragged_In),
            thrower_on_board = sum(On_Board))%>%
  group_by(Match, Round)%>%
  mutate(total_on_board = sum(thrower_on_board), 
         BI = flat_BI / total_on_board)%>%
  select(Match, Thrower, flat_BI, BI)
by_round_BI

by_game_BI <- Cornhole%>%
  group_by(Match, Thrower)%>%
  summarise(flat_BI = sum(Opponent_Other_Bags_Knocked_Off) + sum(Own_Other_Bags_Knocked_Off) + sum(Own_Other_Bags_Dragged_In) + sum(Opponent_Bags_Dragged_In),
            thrower_on_board = sum(On_Board))%>%
  group_by(Match)%>%
  mutate(total_on_board = sum(thrower_on_board), 
         BI = flat_BI / total_on_board)%>%
  select(Match, Thrower, flat_BI, BI, total_on_board)
by_game_BI
```

#### Net Board Score (NBS)


```{r}
by_round_NBS <- Cornhole%>%
  group_by(Match, Round, Thrower)%>%
  summarise(flat_NBS = sum(Opponent_Other_Bags_Knocked_Off) - sum(Own_Other_Bags_Knocked_Off) + 2*sum(Own_Other_Bags_Dragged_In) - 2*sum(Opponent_Bags_Dragged_In))
by_round_NBS

by_game_NBS <- Cornhole%>%
  group_by(Match, Thrower)%>%
  summarise(flat_NBS = sum(Opponent_Other_Bags_Knocked_Off) - sum(Own_Other_Bags_Knocked_Off) + 2*sum(Own_Other_Bags_Dragged_In) - 2*sum(Opponent_Bags_Dragged_In),
            thrower_on_board = sum(On_Board))%>%
  group_by(Match)%>%
  mutate(total_on_board = sum(thrower_on_board), 
         norm_NBS = flat_NBS / total_on_board)%>%
  select(Match, Thrower, flat_NBS, norm_NBS)
by_game_NBS
```
#### Overall Board Management Score (BMS)

```{r}
by_game_BMS <- by_game_BC%>%
  merge(by_game_BI, by = c("Match", "Thrower"))%>%
  merge(by_game_NBS, by = c("Match", "Thrower"))%>%
  merge(by_game_NSAB, by = c("Match", "Thrower"))%>%
  select(-BC)%>%
  mutate(won = as.factor(c(0,1,1,0,0,1,1,0,0,1,0,1,0,1,1,0,0,1)))%>%
  mutate(NBS_per_throw = flat_NBS / total_throws)%>%
  mutate(BMS = norm_NBS + NSAB_per_block)

BMS_by_result <- by_game_BMS%>%
  group_by(won)%>%
  summarise(avg_BMS = mean(BMS),
            avg_NBS = mean(NBS_per_throw),
            avg_NSAB = mean(NSAB_per_block))
BMS_by_result

by_round_BMS <- 
```


## Summary Figures

```{r}
by_game_stats <- by_game_ATS%>%
  merge(by_game_BC, by = c("Match", "Thrower"))%>%
  merge(by_game_BI, by = c("Match", "Thrower"))%>%
  merge(by_game_NBS, by = c("Match", "Thrower"))%>%
  merge(by_game_NSAB, by = c("Match", "Thrower"))%>%
  mutate(won = as.factor(c(0,1,1,0,0,1,1,0,0,1,0,1,0,1,1,0,0,1)))%>%
  select(-total_throws.y)%>%
  rename("total_throws" = total_throws.x)%>%
  mutate(Toss_Score = ATS*total_throws)%>%
  mutate(NBS_per_throw = flat_NBS / total_throws)%>%
  mutate(BMS = NBS_per_throw + NSAB_per_block)%>%
  select(-BC)

# mod1 = glm(won~ BMS + ATS, data = by_game_stats, family = "binomial")
# summary(mod1)

```

```{r}
by_round_stats <- by_round_ATS%>%
  merge(by_round_BC, by = c("Match", "Round", "Thrower"))%>%
  merge(by_round_BI, by = c("Match", "Round", "Thrower"))%>%
  merge(by_round_NBS, by = c("Match", "Round", "Thrower"))%>%
  merge(by_round_NSAB, by = c("Match", "Round", "Thrower"), all.x = TRUE)%>%
  merge(Round_scores, by.x = c("Match", "Round"), by.y = c("Game_Number", "Round_Number"))%>%
  mutate(Points = ifelse(Round_Winner == Thrower, Points_Gained, -Points_Gained))%>%
  mutate(result = case_when(Round_Winner == Thrower ~ 1,
                            Round_Winner == "Tie" ~ 0,
                            TRUE ~ -1))%>%
  replace_na(list(NSAB_per_block = 0))%>%
  select(-c(blocks, total_NSAB))%>%
  mutate(NBS_per_throw = flat_NBS / 4)%>%
  mutate(BMS = NSAB_per_block + NBS_per_throw)

summary(by_round_stats$BMS)

mod_round_points = lm(Points~ BMS + ATS, data = by_round_stats[,c(4,5,6,9,12,14,15)])
summary(mod_round_points)

names(by_game_stats)

# mod_norm = glm(won~., data = by_game_stats[,c(4,6,8,10,11)], family = "binomial")
# summary(mod1_flat)
```

Final Table (Pretty)

```{r}
pretty_final_table <- by_game_stats%>%
  select(-c(norm_NBS, Toss_Score, total_on_board))%>%
  rename("Player" = Thrower, "Total Throws" = total_throws, "Average Toss Score" = ATS, "Blocks" = blocks, "Blocks per Throw" = NBC,  "Bags Affected" = flat_BI, "Board Impact" = BI, "Net Board Score" = flat_NBS, "NBS per Throw" = NBS_per_throw, "Net Score After Block" = total_NSAB, "NSAB per Block" = NSAB_per_block, "Board Management Score" = BMS, "Result" = won)

pretty_final_table <- pretty_final_table[, c(1,2,3,4,9,5,6,7,8,13,10,11,14,12)]

pretty_final_table[, "Average Toss Score"] = round(pretty_final_table$`Average Toss Score`, 3)
pretty_final_table[, "Blocks per Throw"] = round(pretty_final_table$`Blocks per Throw`, 3)
pretty_final_table[, "NBS per Throw"] = round(pretty_final_table$`NBS per Throw`, 3)
pretty_final_table[, "NSAB per Block"] = round(pretty_final_table$`NSAB per Block`, 3)
pretty_final_table[, "Board Management Score"] = round(pretty_final_table$`Board Management Score`, 3)

pretty_final_table[, "Board Impact"] = percent(pretty_final_table$`Board Impact`, .1)

pretty_final_table[, "Result"] = ifelse(pretty_final_table$Result == 1, "Winner", "Loser")

pretty_table_as_dt <- datatable(pretty_final_table)
# print(pretty_table_as_dt)

pretty_final_table
```


